name: Deploy (Develop)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Workflow A"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Remove SSH Key(s)
        continue-on-error: true
        run: ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "hlafaille.xyz"
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: deploy # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Deploy
        run: ssh -i ~/.ssh/deploy -v -o BatchMode=yes ${{ secrets.SSH_USERNAME_HOST }} "${{ secrets.DEPLOY_COMMAND }}"
